---

- name: Install a list of packages
  apt:
    pkg:
      - screen
      - apt-transport-https
    update_cache: yes

- name: remove old repos
  ansible.builtin.file:
    path: /etc/apt/sources.list.d
    state: absent

- name: create /etc/apt/sources.list.d again
  ansible.builtin.file:
    path: /etc/apt/sources.list.d
    owner: root
    group: root
    mode: '0751'
    state: directory

- name: set debian base repo for "{{ debian_release }}"
  ansible.builtin.template:
    src: "templates/sources.list_{{ debian_release }}.j2"
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'
  when: (ansible_distribution == "Debian")

- name: set proxmox repo for "{{ debian_release }}"
  ansible.builtin.template:
    src: "templates/pve_repo.list_{{ debian_release }}.j2"
    dest: /etc/apt/sources.list.d/pve_repo.list
    owner: root
    group: root
    mode: '0644'
  when: (ansible_distribution == "Debian")

- name: apt update to get new package for dist-upgrade
  apt:
    update_cache: yes

- name: set env noninteractive
  shell: env DEBIAN_FRONTEND=noninteractive

- name: set env apt list changes to mail
  shell: env APT_LISTCHANGES_FRONTEND=mail

- name: upgrade to "{{ debian_release }}"
  apt:
    upgrade: dist
    update_cache: yes
    dpkg_options: 'force-confdef,force-confold'
